// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SunService.Infra.Data.Db.SqlServer.Ef.Common;

#nullable disable

namespace SunService.Infra.Data.Db.SqlServer.Ef.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "تهران"
                        },
                        new
                        {
                            Id = 2,
                            Title = "مشهد"
                        },
                        new
                        {
                            Id = 3,
                            Title = "اصفهان"
                        },
                        new
                        {
                            Id = 4,
                            Title = "شیراز"
                        },
                        new
                        {
                            Id = 5,
                            Title = "تبریز"
                        },
                        new
                        {
                            Id = 6,
                            Title = "کرج"
                        },
                        new
                        {
                            Id = 7,
                            Title = "قم"
                        },
                        new
                        {
                            Id = 8,
                            Title = "اهواز"
                        },
                        new
                        {
                            Id = 9,
                            Title = "رشت"
                        },
                        new
                        {
                            Id = 10,
                            Title = "کرمانشاه"
                        },
                        new
                        {
                            Id = 11,
                            Title = "زاهدان"
                        },
                        new
                        {
                            Id = 12,
                            Title = "ارومیه"
                        },
                        new
                        {
                            Id = 13,
                            Title = "یزد"
                        },
                        new
                        {
                            Id = 14,
                            Title = "همدان"
                        },
                        new
                        {
                            Id = 15,
                            Title = "قزوین"
                        },
                        new
                        {
                            Id = 16,
                            Title = "سنندج"
                        },
                        new
                        {
                            Id = 17,
                            Title = "بندرعباس"
                        },
                        new
                        {
                            Id = 18,
                            Title = "زنجان"
                        },
                        new
                        {
                            Id = 19,
                            Title = "ساری"
                        },
                        new
                        {
                            Id = 20,
                            Title = "بوشهر"
                        },
                        new
                        {
                            Id = 21,
                            Title = "بجنورد"
                        },
                        new
                        {
                            Id = 22,
                            Title = "گرگان"
                        },
                        new
                        {
                            Id = 23,
                            Title = "کرمان"
                        },
                        new
                        {
                            Id = 24,
                            Title = "خرم آباد"
                        },
                        new
                        {
                            Id = 25,
                            Title = "سمنان"
                        },
                        new
                        {
                            Id = 26,
                            Title = "بیرجند"
                        },
                        new
                        {
                            Id = 27,
                            Title = "اراک"
                        },
                        new
                        {
                            Id = 28,
                            Title = "اردبیل"
                        },
                        new
                        {
                            Id = 29,
                            Title = "ایلام"
                        },
                        new
                        {
                            Id = 30,
                            Title = "شهرکرد"
                        },
                        new
                        {
                            Id = 31,
                            Title = "یاسوج"
                        });
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Expert",
                            NormalizedName = "EXPERT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "\\Images\\Category\\clean-mainCategory-icon.jpg",
                            Title = "تمیزکاری"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "\\Images\\Category\\Building-mainCategory-icon.jpg",
                            Title = "ساختمان"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "\\Images\\Category\\Repairs-mainCategory-icon.jpg",
                            Title = "تعمیرات اشیا"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "\\Images\\Category\\Cargo-transportation-mainCategory-icon.jpg",
                            Title = "اسباب کشی و حمل بار"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "\\Images\\Category\\Car-mainCategory-icon.jpg",
                            Title = "خودرو"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "\\Images\\Category\\Beauty-mainCategory-icon.jpg",
                            Title = "سلامت و زیبایی"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "\\Images\\Category\\Complexes-mainCategory-icon.jpg",
                            Title = "سازمان ها و مجتمع ها"
                        });
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.ExpertService", b =>
                {
                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.HasKey("ExpertId", "HomeServiceId");

                    b.HasIndex("HomeServiceId");

                    b.ToTable("ExpertServices");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.HomeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasePrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberVisits")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("HomeServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 2000000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Cleaning-and-catering-homeservice_image.jpg",
                            NumberVisits = 202,
                            SubCategoryId = 1,
                            Title = "سرویس نظافت فوری"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 3500000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Washing-homeservice_image.jpg",
                            NumberVisits = 145,
                            SubCategoryId = 2,
                            Title = "قالیشویی"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 4000000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Cabinet-homeservice_image.jpg",
                            NumberVisits = 128,
                            SubCategoryId = 3,
                            Title = "نجاری"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 2500000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Plumbing-homeservice_image.jpg",
                            NumberVisits = 235,
                            SubCategoryId = 4,
                            Title = "نصب و تعمیر شیرآلات"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 1000000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Home-appliances-homeservice_image.jpg",
                            NumberVisits = 147,
                            SubCategoryId = 5,
                            Title = "نصب و تعمیر ماشین لباسشویی"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 1000000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Cooling and heating-homeservice_image.jpg",
                            NumberVisits = 147,
                            SubCategoryId = 6,
                            Title = "تعمیر کولر گازی"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 4000000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Freight-homeservice_image.jpg",
                            NumberVisits = 117,
                            SubCategoryId = 7,
                            Title = "سرویس بسته بندی"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 2500000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Car-repair-homeservice_image.jpg",
                            NumberVisits = 149,
                            SubCategoryId = 8,
                            Title = "امداد خودرو"
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 3500000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Car-wash-homeservice_image.jpg",
                            NumberVisits = 122,
                            SubCategoryId = 9,
                            Title = "کارواش با آب"
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 4000000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Medicine-and-nursing-homeservice_image.jpg",
                            NumberVisits = 224,
                            SubCategoryId = 10,
                            Title = "پرستاری و تزریقات"
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 5000000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Women's-beauty-homeservice_image.jpg",
                            NumberVisits = 149,
                            SubCategoryId = 11,
                            Title = "زیبایی بانوان"
                        },
                        new
                        {
                            Id = 12,
                            BasePrice = 2200000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Corporate services-homeservice_image.jpg",
                            NumberVisits = 110,
                            SubCategoryId = 12,
                            Title = "خدمات شرکتی ویژه شرکت های کوچک"
                        },
                        new
                        {
                            Id = 13,
                            BasePrice = 3400000,
                            Description = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است",
                            ImagePath = "\\Images\\Homeservice\\Providing-human-resources-homeservice_image.jpg",
                            NumberVisits = 132,
                            SubCategoryId = 13,
                            Title = "استخدام خدمتکار"
                        });
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OfferDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PriceOffer")
                        .HasColumnType("int");

                    b.Property<bool>("StateOffer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("OrderId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImplementationDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("ImplementationTime")
                        .HasColumnType("time");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<int>("OrderHomeServiceStatus")
                        .HasColumnType("int");

                    b.Property<bool>("StateOrder")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("HomeServiceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Title = "نظافت و پذیرایی"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Title = "شستشو"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Title = "چوب و کابینت"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Title = "لوله کشی"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Title = "نصب و تعمیر لوازم خانگی"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Title = "سرمایش و گرمایش"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Title = "باربری و جابه جایی"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            Title = "خدمات و تعمیرات خودرو"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Title = "کارواش خودرو"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 6,
                            Title = "پزشکی و پرستاری"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Title = "زیبایی بانوان"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            Title = "خدمات شرکتی"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Title = "تامین نیروی انسانی"
                        });
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpertServiceExpertId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpertServiceHomeServiceId")
                        .HasColumnType("int");

                    b.Property<int>("HomeServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("HomeServiceId");

                    b.HasIndex("ExpertServiceExpertId", "ExpertServiceHomeServiceId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShabaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusUser")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            CityId = 1,
                            ConcurrencyStamp = "b555eb19-6186-4118-a10f-f9a602772742",
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Mobile = "09196043564",
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOMx4ljStIJw7A7+pqClXCuuweBw8mUvTUxd1cmXYNha1Hbf5sSCIALElHL4XD24sg==",
                            PhoneNumberConfirmed = false,
                            RegisterAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 1,
                            SecurityStamp = "54855c37-20d0-4e82-976c-f166aba3f7c4",
                            StatusUser = false,
                            TwoFactorEnabled = false,
                            UserName = "Admin@gmail.com"
                        });
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.Customer", b =>
                {
                    b.HasBaseType("SunService.Domain.Core.SunServices.UserS.Entities.User");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.Expert", b =>
                {
                    b.HasBaseType("SunService.Domain.Core.SunServices.UserS.Entities.User");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.ToTable("Experts", (string)null);
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.HService.Entities.Order", "Order")
                        .WithMany("Images")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.ExpertService", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.Expert", "Expert")
                        .WithMany("ExpertServices")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SunService.Domain.Core.SunServices.HService.Entities.HomeService", "HomeService")
                        .WithMany("ExpertServices")
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("HomeService");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.HomeService", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.HService.Entities.SubCategory", "SubCategory")
                        .WithMany("HomeServices")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.Offer", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.Expert", "Expert")
                        .WithMany("Offers")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SunService.Domain.Core.SunServices.HService.Entities.Order", "Order")
                        .WithMany("Offers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.Order", b =>
                {
                    b.HasOne("City", "City")
                        .WithMany("orders")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.Customer", "Customer")
                        .WithMany("orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.Expert", "Expert")
                        .WithMany("Orders")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SunService.Domain.Core.SunServices.HService.Entities.HomeService", "HomeService")
                        .WithMany("orders")
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("HomeService");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.SubCategory", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.HService.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.Rating", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.Customer", "Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.Expert", "Expert")
                        .WithMany("Ratings")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SunService.Domain.Core.SunServices.HService.Entities.HomeService", "HomeService")
                        .WithMany("Ratings")
                        .HasForeignKey("HomeServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SunService.Domain.Core.SunServices.HService.Entities.ExpertService", null)
                        .WithMany("Ratings")
                        .HasForeignKey("ExpertServiceExpertId", "ExpertServiceHomeServiceId");

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("HomeService");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.User", b =>
                {
                    b.HasOne("City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.Customer", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("SunService.Domain.Core.SunServices.UserS.Entities.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.Expert", b =>
                {
                    b.HasOne("SunService.Domain.Core.SunServices.UserS.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("SunService.Domain.Core.SunServices.UserS.Entities.Expert", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("City", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("orders");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.ExpertService", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.HomeService", b =>
                {
                    b.Navigation("ExpertServices");

                    b.Navigation("Ratings");

                    b.Navigation("orders");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.Order", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.HService.Entities.SubCategory", b =>
                {
                    b.Navigation("HomeServices");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.Customer", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("orders");
                });

            modelBuilder.Entity("SunService.Domain.Core.SunServices.UserS.Entities.Expert", b =>
                {
                    b.Navigation("ExpertServices");

                    b.Navigation("Offers");

                    b.Navigation("Orders");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
