<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="SunServices\BaseEntities\" />
    <Folder Include="SunServices\HService\" />
    <Folder Include="SunServices\UserS\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\SunService.Domain.Core\SunService.Domain.Core.csproj" />
  </ItemGroup>

</Project>
